from pathlib import Path
import json
from html import escape
D=Path(__file__).parent/'dist'
courses=[dict(slug='inclusive-preschool',title='Инклюзия в дошкольных организациях',hours=80,tag='Для воспитателей',img='inclusive.webp',desc='Практические подходы к обучению и сопровождению детей с особыми образовательными потребностями.',modules=['Основы инклюзивной образовательной среды','Понимание индивидуальных потребностей ребёнка','Адаптация занятий и развивающих материалов','Взаимодействие с семьёй и специалистами']),dict(slug='bullying-prevention',title='Профилактика буллинга в образовании',hours=72,tag='Для педагогов',img='hero.webp',desc='Как распознавать травлю, поддерживать детей и создавать безопасную образовательную среду.',modules=['Буллинг: признаки и участники','Профилактика и работа с коллективом','Поддержка ребёнка и диалог с родителями','Разбор практических ситуаций']),dict(slug='antiterror-education',title='Антитеррористическая защищённость объектов образования',hours=80,tag='Для организаций',img='safety.webp',desc='Подготовка работников к предупреждению угроз и согласованным действиям в чрезвычайных ситуациях.',modules=['Организация безопасности образовательного объекта','Профилактические мероприятия','Действия персонала при угрозе','Психологическая поддержка и взаимодействие'])]
nav='<a href="/courses/">Курсы</a><a href="/organizations/">Для организаций</a><a href="/about/">О центре</a><a href="/materials/">Материалы</a><a href="/contacts/">Контакты</a>'
brand='<a class="brand" href="/">Өркендеу<span>УЧЕБНО-МЕТОДИЧЕСКИЙ ЦЕНТР</span></a>'
def btn(text='Получить консультацию',context='Консультация',cls='gold'):
 return f'<button class="btn {cls}" data-apply="{escape(context)}">{text}<span aria-hidden="true">↗</span></button>'
def card(c):
 return f'<article class="course"><a class="course-photo" href="/courses/{c["slug"]}/"><img src="/assets/{c["img"]}" alt="Обучение педагогов" loading="lazy"><span class="hours">{c["hours"]} часов</span></a><div class="course-body"><p class="eyebrow">{c["tag"]}</p><h3><a href="/courses/{c["slug"]}/">{c["title"]}</a></h3><p class="muted">Онлайн · Русский / Қазақша</p><a class="text-link" href="/courses/{c["slug"]}/">Подробнее о курсе <span>↗</span></a></div></article>'
def cert(i):
 return f'<button class="certificate cert-{i}" data-document="Сертификат — образец {i}" aria-label="Увеличить образец сертификата {i}"><span class="cert-brand">Өркендеу</span><small>УЧЕБНО-МЕТОДИЧЕСКИЙ ЦЕНТР</small><strong>СЕРТИФИКАТ</strong><span>о прохождении курса повышения квалификации</span><b>ОБРАЗЕЦ</b><small>Содержание документа будет заменено оригиналом</small></button>'
def letter(i):
 dimensions=[(308,357),(306,354),(304,354)]
 w,h=dimensions[i-1]
 return f'<button class="letter-card" data-document="Благодарственное письмо — образец {i}" data-document-image="/assets/letter-example-{i}.png"><img class="letter-scan" src="/assets/letter-example-{i}.png" alt="Образец благодарственного письма {i}" width="{w}" height="{h}" loading="lazy"><span>Благодарственное письмо <span>⤢</span></span></button>'

materials=[('Методические рекомендации','Практика','inclusive.webp','Как адаптировать занятие для разных потребностей детей','Начните с одной общей цели занятия. Предложите детям разные способы участия: устный ответ, рисунок, выбор карточки или практическое действие. Наблюдайте, какой формат помогает каждому ребёнку включиться в работу.'),('Материалы для воспитателей','Дошкольное образование','hero.webp','Диалог с родителями: встреча с общей целью','Перед встречей определите конкретную тему. Начните с наблюдений о сильных сторонах ребёнка, затем обсудите трудности без оценочных ярлыков. Завершите разговор одной совместной договорённостью и датой следующего обсуждения.'),('Практика безопасной школы','Безопасная среда','safety.webp','Как поддержать ребёнка, который сообщил о травле','Выслушайте ребёнка спокойно и поблагодарите за доверие. Не обещайте абсолютную тайну: объясните, что для помощи потребуется участие ответственных взрослых. Зафиксируйте сообщённые факты и действуйте по процедурам вашей организации.')]
def matcards():
 return ''.join(f'<a class="material" href="/materials/article-{i+1}/"><img src="/assets/{m[2]}" alt="" loading="lazy"><div><p class="eyebrow">{m[1]}</p><h3>{m[0]}</h3><span>Читать материал ↗</span></div></a>' for i,m in enumerate(materials))
modal='''<dialog id="apply-dialog"><button class="close" aria-label="Закрыть">×</button><p class="eyebrow">ДАВАЙТЕ ОБСУДИМ ОБУЧЕНИЕ</p><h2>Поможем выбрать программу</h2><p id="apply-context"></p><p class="demo-note">Демонстрационная форма: данные не отправляются и не сохраняются.</p><form id="application"><label>Ваше имя<input name="name" required autocomplete="given-name" placeholder="Как к вам обращаться"></label><label>Телефон<input name="phone" required type="tel" autocomplete="tel" pattern="[0-9+\\s\\x28\\x29\\x2D]{10,20}" placeholder="+7 (___) ___-__-__"></label><label>Организация<input name="organization" placeholder="Название организации"></label><button class="btn gold" type="submit">Проверить заявку <span>↗</span></button><p id="form-result" role="status"></p></form></dialog><dialog id="document-dialog"><button class="close" aria-label="Закрыть">×</button><h2 id="document-title"></h2><div id="document-content"></div><p class="muted" id="document-note">Демонстрационный образец. Здесь можно разместить ваш оригинал.</p></dialog>'''
def page(title,body):
 return f'''<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>{title} — Өркендеу</title><meta name="description" content="Повышение квалификации специалистов образования, здравоохранения и организаций. Учебно-методический центр Өркендеу."><link rel="icon" type="image/svg+xml" href="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Crect width='64' height='64' rx='14' fill='%23142c46'/%3E%3Ctext x='32' y='46' text-anchor='middle' font-size='46' fill='%23c6a263'%3EӨ%3C/text%3E%3C/svg%3E"><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head><body><a class="skip" href="#main">Перейти к содержанию</a><header><div class="header-inner">{brand}<nav aria-label="Основное меню">{nav}</nav><a class="login" href="https://lms.orkendey.kz/" target="_blank" rel="noopener">Войти в LMS ↗</a><button class="menu" aria-label="Открыть меню" aria-expanded="false">☰</button></div></header><main id="main">{body}</main><footer><div class="container footer-top">{brand}<div>{nav}</div><div>Алматы · Астана<br><a href="mailto:edu@orkendey.kz">edu@orkendey.kz</a></div></div><div class="container footer-bottom"><span>© Өркендеу · Учимся. Развиваемся. Меняем.</span><span>Демоверсия · Документы и фотографии — образцы</span></div></footer>{modal}</body></html>'''
def write(route,title,body):
 p=D/route/'index.html';p.parent.mkdir(parents=True,exist_ok=True);p.write_text(page(title,body))
def heading(eye,title,text=''):
 return f'<section class="page-head container"><p class="eyebrow">{eye}</p><h1>{title}</h1><p>{text}</p></section>'
steps=[('01','Выберите курс','Найдите программу под свои задачи.'),('02','Оставьте заявку','Обсудите условия с нашим специалистом.'),('03','Получите доступ','Войдите в личный кабинет на платформе.'),('04','Пройдите обучение','Изучайте материалы и выполняйте тесты.'),('05','Получите сертификат','После успешного завершения программы.')]
from home import build_home
build_home(D,modal,courses)
write('courses','Каталог курсов',heading('ПРОФЕССИОНАЛЬНОЕ РАЗВИТИЕ','Найдите свою программу','Три приоритетные программы учебного центра в демонстрационном каталоге.')+'<section class="container section"><label class="search-label">Поиск по курсам<input id="course-search" type="search" placeholder="Название курса или аудитория"></label><div class="filters"><button class="active" data-filter="all">Все программы</button><button data-filter="Для воспитателей">Воспитателям</button><button data-filter="Для педагогов">Педагогам</button><button data-filter="Для организаций">Организациям</button></div><div class="course-grid" id="catalog">'+''.join(card(c) for c in courses)+'</div><p id="no-results" hidden>Подходящих курсов не найдено. Попробуйте другое название.</p></section>')
for c in courses:
 write('courses/'+c['slug'],c['title'],f'<section class="course-detail container"><div><a class="text-link" href="/courses/">← Все курсы</a><p class="eyebrow">{c["tag"]} · {c["hours"]} часов</p><h1>{c["title"]}</h1><p class="lead">{c["desc"]}</p><div class="detail-tags"><span>Онлайн</span><span>Русский / Қазақша</span><span>Сертификат</span></div>{btn("Оставить заявку",c["title"])}</div><img src="/assets/{c["img"]}" alt="Обучение педагогов"></section><section class="container section narrow"><p class="eyebrow">СОДЕРЖАНИЕ ОБУЧЕНИЯ</p><h2>Программа курса</h2><p class="demo-note">Пример структуры для демонстрации. Итоговая программа и условия уточняются при записи.</p>'+''.join(f'<details><summary>{i+1:02d} · {m}</summary><p>Тематическая лекция, практические примеры и материалы для самостоятельной работы.</p></details>' for i,m in enumerate(c['modules']))+'</section>')
write('organizations','Для организаций',heading('ОБУЧЕНИЕ КОЛЛЕКТИВОВ','Развивайте команду вместе','Программы для организаций образования, здравоохранения и частного сектора.')+'<section class="container section two-col"><img class="rounded-image" src="/assets/safety.webp" alt="Обучение коллектива"><div><h2>От задачи — к программе</h2><p>Расскажите, какие специалисты будут учиться и какие темы важны вашей организации. Мы поможем подобрать программы и обсудить порядок обучения.</p><ul class="benefits"><li>Подбор курсов для сотрудников</li><li>Обучение на русском и казахском языках</li><li>Лекции, материалы и тестирование онлайн</li><li>Документы по итогам обучения</li></ul>'+btn('Обсудить обучение','Обучение коллектива')+'</div></section>')
write('about','О центре',heading('УЧЕБНО-МЕТОДИЧЕСКИЙ ЦЕНТР','Өркендеу — пространство развития','Помогаем специалистам образования, здравоохранения и организаций осваивать знания для ежедневной работы.')+'<section class="container section two-col"><img class="rounded-image" src="/assets/hero-classroom-1536.webp" srcset="/assets/hero-classroom-768.webp 768w, /assets/hero-classroom-1024.webp 1024w, /assets/hero-classroom-1536.webp 1536w" sizes="(max-width:760px) 100vw, 50vw" width="1536" height="1024" alt="Педагоги на семинаре"><div><h2>Знания, которые становятся практикой</h2><p>Наши направления — профессиональное обучение, безопасность и охрана труда, инклюзивное образование, профилактика буллинга и другие программы для специалистов и команд.</p><p>Обучаем индивидуальных слушателей и коллективы организаций. Программы доступны онлайн на русском и казахском языках.</p><a class="btn gold" href="/courses/">Познакомиться с курсами ↗</a></div></section>')
write('letters','Благодарственные письма',heading('НАМ ДОВЕРЯЮТ','Благодарственные письма','Демонстрационная галерея. Оригинальные сканы будут размещены после загрузки.')+'<section class="container section"><div class="letters-grid light">'+''.join(letter(i) for i in range(1,4))+'</div></section>')
write('materials','Полезные материалы',heading('ПРИМЕНЯЙТЕ В РАБОТЕ','Полезные материалы','Короткие практические заметки для педагогов и воспитателей.')+'<section class="container section material-grid">'+matcards()+'</section>')
for i,m in enumerate(materials):
 write(f'materials/article-{i+1}',m[3],heading(m[1],m[3])+'<article class="container section narrow article"><img class="rounded-image" src="/assets/'+m[2]+'" alt=""><p class="lead">'+m[4]+'</p><p class="demo-note">Пример материала для демоверсии сайта.</p><a class="text-link" href="/materials/">← Все материалы</a></article>')
write('contacts','Контакты',heading('БУДЕМ НА СВЯЗИ','Обсудим ваши задачи','Обучение по всему Казахстану. Алматы · Астана.')+'<section class="container section contact-box"><div><p class="eyebrow">ЭЛЕКТРОННАЯ ПОЧТА</p><a class="contact-email" href="mailto:edu@orkendey.kz">edu@orkendey.kz</a><p>Для вопросов о программах и обучении коллективов.</p></div>'+btn()+'</section>')
write('certificate','Проверка сертификата',heading('ПОДЛИННОСТЬ ДОКУМЕНТА','Проверка сертификата','Используйте QR-код на вашем сертификате для перехода к записи о документе.')+'<section class="container section narrow"><p>Демонстрационный сайт не подключён к реестру сертификатов. Для проверки документа перейдите на действующую платформу учебного центра или обратитесь по электронной почте.</p><div class="actions"><a class="btn gold" href="https://lms.orkendey.kz/" target="_blank" rel="noopener">Открыть платформу ↗</a><a class="btn outline" href="mailto:edu@orkendey.kz">Написать в центр</a></div></section>')
(D/'404.html').write_text(page('Страница не найдена',heading('404','Эта страница не найдена')+'<div class="container section"><a class="btn gold" href="/">На главную</a></div>'))

from catalog import build_catalog
build_catalog(D,page,btn)
